name: add

on:
  issues:
    types: [opened, edited]

jobs:
  add-bookmark:
    if: "contains(github.event.issue.labels.*.name, 'add') && !contains(github.event.issue.labels.*.name, 'remove')"
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name as environment variable
        run: echo "NEW_BRANCH_NAME=add-bookmark-$(date '+%s')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git switch -c ${{ env.NEW_BRANCH_NAME }}

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Add bookmark
        run: deno task bookmark:add "${{ github.event.issue.body }}"

      - name: Format
        run: deno task fmt:data

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "./data/*.ts"
          branch: ${{ env.NEW_BRANCH_NAME }}
          commit_message: "ðŸ”– ãƒ–ãƒƒã‚¯ãƒžãƒ¼ã‚¯ã‚’è¿½åŠ  #${{ github.event.issue.number }}"

      - name: Create pull request
        run: gh pr create --title "ðŸ”– ãƒ–ãƒƒã‚¯ãƒžãƒ¼ã‚¯ã‚’è¿½åŠ " --body "Closes #${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
